# np.linalg.norm

In [1]:
import numpy as np

In [2]:
a=np.arange(9).reshape((3,3))
b=-a.copy()

In [5]:
a


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
b

array([[ 0, -1, -2],
       [-3, -4, -5],
       [-6, -7, -8]])

In [8]:
np.linalg.norm(a)

14.2828568570857

In [9]:
np.linalg.norm(b)

14.2828568570857

两者的结果一样。因为其计算方法为 $ ||A||_F=[\sum_{i,j}{{a_{i,j}}^2}]^{1/2}$

上式也表明就算没有reshape结果也是一样的，也就是**只要元素值的绝对值一样，无论这个矩阵是什么形状的，他们的元素处在哪里，结果都是一样的**,具体如下

In [11]:
c=np.arange(9)
np.linalg.norm(c)

14.2828568570857

In [12]:
np.random.shuffle(c)

In [13]:
c

array([4, 0, 8, 2, 5, 7, 3, 1, 6])

In [14]:
np.linalg.norm(c)

14.2828568570857