## np一些函数的用法

### np.random.shuffle()

In [1]:
import numpy as np

In [7]:
a=np.arange(10)
print('a:',a)
print(type(a))
print('====================')
np.random.shuffle(a)
print('after shuffling a:',a)

a: [0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
after shuffling a: [8 7 2 0 3 1 6 9 5 4]


需要注意的是，shuffle 函数直接改变原有数组，此函数没有返回值，这一点容易忘记

### np.reshpae()


In [8]:
b=np.arange(12)
c=b.reshape((3,4))
print('b:',b)
print('c:',c)

b: [ 0  1  2  3  4  5  6  7  8  9 10 11]
c: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [9]:
d=b.reshape((3,-1))
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
e=b.reshape((-1,4))
e

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
f=b.reshape((1,-1))
f

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [17]:
h=f.reshape([3,4])
h

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

reshpae函数的输入参数为一个元组或者列表，如果元组中有一个元素为-1，则这个位置的数由计算机自动计算完成，比如变量d,e

### np.argmin, np.amax

In [28]:
aa=np.arange(20)
np.random.shuffle(aa)
aa=aa.reshape((4,5))
aa

array([[ 9, 14,  4, 15, 16],
       [ 0,  5, 17, 11,  8],
       [19,  1, 10,  7, 18],
       [12,  3,  2, 13,  6]])

In [29]:
aa.argmin(axis=0)

array([1, 2, 3, 2, 3], dtype=int64)

In [30]:
aa.argmin(axis=1)

array([2, 0, 1, 2], dtype=int64)

In [31]:
aa.argmin()

5

In [33]:
bb=np.arange(24)
np.random.shuffle(bb)
bb=bb.reshape((2,3,4))
bb

array([[[22, 23, 12,  2],
        [15,  5, 18, 16],
        [ 0,  4, 17, 10]],

       [[14,  9,  1, 21],
        [20, 19,  6, 13],
        [ 7, 11,  3,  8]]])

In [34]:
bb.argmin(axis=0)

array([[1, 1, 1, 0],
       [0, 0, 1, 1],
       [0, 0, 1, 1]], dtype=int64)

In [35]:
bb.argmin(axis=1)

array([[2, 2, 0, 0],
       [2, 0, 0, 2]], dtype=int64)

In [36]:
bb.argmin(axis=2)

array([[3, 1, 0],
       [2, 2, 2]], dtype=int64)

此函数返回数组中最小值元素的索引，如果axis没有给定参数，则给出整个数组中最小的值，如果数组是一个二维的，axis=0,按列比较，axis=1按行比较
三维的话，0表示按高比较，1表示按列比较，2表示按行比较

In [39]:
cc=aa
cc

array([[ 9, 14,  4, 15, 16],
       [ 0,  5, 17, 11,  8],
       [19,  1, 10,  7, 18],
       [12,  3,  2, 13,  6]])

In [41]:
np.amax(cc)

19

In [42]:
np.amax(cc,axis=0)

array([19, 14, 17, 15, 18])

In [43]:
np.amax(cc,axis=1)

array([16, 17, 19, 13])

此函数与argmin略有不同，调用的方式不同，但是axis的用法是一致的；返回值不同，一个是返回索引，一个是返回相应的值。