对于numpy类型的矩阵数据，如果想把其中的某一列提取出来还是列那该怎么做呢

In [1]:
import numpy as np

In [2]:
a=np.arange(16).reshape(4,4)

In [3]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [4]:
b=a[:,1]
c=a[:,1:2]

In [5]:
b

array([ 1,  5,  9, 13])

In [6]:
c

array([[ 1],
       [ 5],
       [ 9],
       [13]])

所以如果想提取之后然后是列，那么就需要使用c的那种形式