怎么使用np.insert()

In [1]:
import numpy as np

In [3]:
a=np.arange(20).reshape(5,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [4]:
b=np.insert(a,2,100)
b

array([  0,   1, 100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,
        12,  13,  14,  15,  16,  17,  18,  19])

In [5]:
c=np.insert(a,2,100,axis=1)
c

array([[  0,   1, 100,   2,   3],
       [  4,   5, 100,   6,   7],
       [  8,   9, 100,  10,  11],
       [ 12,  13, 100,  14,  15],
       [ 16,  17, 100,  18,  19]])

1. 第一个参数是一个数组
2. 第二个参数是一个整数或者一个列表，表示需要insert的位置
3. 第三个参数是一个整数，或者一个列表，表示需要插入的值
4. 第四个参数表示插入的方向，默认为0，表示横向插入，axis=1时，表示按列插入
 
**注意：** 当axis=1时，如果第三个参数是一个列表，那么列表的长度需要和第一个参数数组的列长度一样 

**注意：** 当axis=0时，如果第第二个参数是一个列表，那么第三个也应当是一个与其长度一样的列表或者一个整数

In [6]:
d=np.insert(a,2,[100,200])
d

array([  0,   1, 100, 200,   2,   3,   4,   5,   6,   7,   8,   9,  10,
        11,  12,  13,  14,  15,  16,  17,  18,  19])

In [8]:
f=np.insert(a,[2,5],[100,200])
f

array([  0,   1, 100,   2,   3,   4, 200,   5,   6,   7,   8,   9,  10,
        11,  12,  13,  14,  15,  16,  17,  18,  19])

In [9]:
g=np.insert(a,[2,5],[100,300,500])
g

ValueError: shape mismatch: value array of shape (3,) could not be broadcast to indexing result of shape (2,)

In [10]:
h=np.insert(a,[2,5],10)
h

array([ 0,  1, 10,  2,  3,  4, 10,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,
       15, 16, 17, 18, 19])

In [7]:
e=np.insert(a,2,[100,200],axis=1)
e

ValueError: could not broadcast input array from shape (2,1) into shape (5,1)